[package]
name = "learnopengl-1-3-4-shaders_exercise1"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gl.workspace = true
glfw.workspace = true
learnopengl-shared = { path = "../../../shared" }
