[package]
name = "learnopengl-1-1-2-hello_window_clear"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gl.workspace = true
glfw.workspace = true
