[package]
name = "learnopengl-4-9-1-geometry_shader_houses"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gl.workspace = true
glfw.workspace = true
learnopengl-shared = { path = "../../../shared" }
