[package]
name = "learnopengl-1-2-2-hello_triangle_indexed"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gl.workspace = true
glfw.workspace = true
