[package]
name = "learnopengl-1-1-1-hello_window"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gl.workspace = true
glfw.workspace = true
