[package]
name = "learnopengl-5-9-ssao"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gl.workspace = true
glfw.workspace = true
nalgebra-glm.workspace = true
lazy_static.workspace = true
rand.workspace = true
learnopengl-shared = { path = "../../../shared" }
