[package]
name = "learnopengl-1-4-1-textures"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gl.workspace = true
glfw.workspace = true
image.workspace = true
learnopengl-shared = { path = "../../../shared" }
