[package]
name = "learnopengl-1-3-2-shaders_interpolation"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gl.workspace = true
glfw.workspace = true
