[package]
name = "learnopengl-1-3-3-shaders_class"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gl.workspace = true
glfw.workspace = true
learnopengl-shared = { path = "../../../shared" }
