[package]
name = "learnopengl-4-10-1-instancing_quads"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gl.workspace = true
glfw.workspace = true
nalgebra-glm.workspace = true
learnopengl-shared = { path = "../../../shared" }
