[package]
name = "learnopengl-7-3-2d_game"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gl.workspace = true
glfw.workspace = true
nalgebra-glm.workspace = true
lazy_static.workspace = true
rand.workspace = true
freetype.workspace = true
rodio.workspace = true
learnopengl-shared = { path = "../../../shared" }
