[package]
name = "learnopengl-5-8-1-deferred_shading"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gl.workspace = true
glfw.workspace = true
image.workspace = true
nalgebra-glm.workspace = true
lazy_static.workspace = true
rand.workspace = true
rand_pcg.workspace = true
learnopengl-shared = { path = "../../../shared" }
