[package]
name = "learnopengl-shared-ex"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gl.workspace = true
nalgebra-glm.workspace = true
russimp.workspace = true
learnopengl-shared = { path = "../shared" }
