[package]
name = "learnopengl-1-2-3-hello_triangle_exercise1"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gl.workspace = true
glfw.workspace = true
